# 参数说明：

# 定时从缓存区里取数据的频率
receive_t : 0.04

##############################################################################
##############
### 任务一 ###
##############
# 巡线舵机转角比例
follow_angular_ratio_I : 2.3
# 巡线速度
follow_linear_speed_I : 0.5
# 避障动作阈值【应大于下者】
ob_bottom_th_I : 290
# 进入避障程序阈值【应小于上者】
ob_bottom_th_in_I : 280
# 避障角度比例
avoid_angular_ratio_I : 1.0
# 避障速度
avoid_linear_speed_I : 0.2
# 开始回调次数判断【超过则进入modify程序】
modify_cnt_th_I : 25
# modify中直线行走时间
sleep_time_I : 0.4
# 往回拐的舵机角度比例
modify_ratio_I : 0.6
# 看到线的次数超过该值时结束modify，继续巡线
line_cnt_th_I : 1500
##############################################################################

##############################################################################
##############
### 任务三 ###
##############
# 巡线舵机转角比例
follow_angular_ratio_III : 2.3
# 巡线速度
follow_linear_speed_III : 0.5
# 避障动作阈值【应大于下者】
ob_bottom_th_III : 290
# 进入避障程序阈值【应小于上者】
ob_bottom_th_in_III : 280
# 避障角度比例
avoid_angular_ratio_III : 1.0
# 避障速度
avoid_linear_speed_III : 0.2
# 开始回调次数判断【超过则进入modify程序】
modify_cnt_th_III : 25
# modify中直线行走时间
sleep_time_III : 0.4
# 往回拐的舵机角度比例
modify_ratio_III : 0.6
# 看到线的次数超过该值时结束modify，继续巡线
line_cnt_th_III : 1500
##############################################################################

# 二维码识别次数【超过即停下】
QR_cnt_th:=1000 : 1000
# 线与障碍物中心x方向距离差小于该值时认为障碍物在线正中
line_ob_x_th : 20

# 看到一定次数的P且无障碍物，进入停车
P_cnt_th : 50
# 是否靠近过P的判断依据
P_bottom_th : 350
# 接近P的速度
park_s_close : 0.3
# 在P上调整的速度
park_s_stop : 0.2
# 停车过程中的角度比例
park_angular_ratio : 2.0
# 已经接近过P且已经看不到P的次数，即结束判断
end_cnt_th : 50